# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - uses: actions/upload-artifact@v4
      with:
        name: build-dist
        path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: deployment

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-dist
          
      - name: Load ssh key
        run: echo ${{ secrets.SSH_KEY }} > ssh_key.txt
        
      - run: chmod 600 ssh_key.txt
        
      - name: Sync folders
        run: rsync -zv -e 'ssh -i ssh_key.txt' build-dist ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/public_html
        
      - name: Clean key
        run: rm ssh_key.txt
